# Generated by Django 3.1.4 on 2022-11-20 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_auto_20221120_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='mutiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='multiple/')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_app.post')),
            ],
        ),
    ]
